### PR TITLE
feat: Implement Rc TypeInfo ✨

### PR DESCRIPTION
**Pull request by EvolveArt**
I have a merkle tree implementation that uses Rc and I want to store that within my substrate runtime but it's not possible so let make it happen!

### CODE REVIEW

**Review by jsdw — APPROVED** [review]

**Review by niklasad1 — APPROVED** [review]

**Comment by EvolveArt** [comment]
hey @niklasad1 want me to bump the version before merging ?

**Comment by EvolveArt** [comment]
Clippy seems to be complaining for no reasons too

**Comment by jsdw** [comment]
Cargo lock is meaningless in library crates (upstream dependencies will ignore it and generate their own cargo locks instead etc)

The clippy errors are possibly just new errors that appeared since rust was updated. The cleanest approach would be another PR that runs a clippy --fix etc to sort these out :)

**Comment by EvolveArt** [comment]
Sounds good thanks for the quick answer @jsdw !

**Comment by jsdw** [comment]
Oh and no need for any version bumps; that'll be taken care of when we do a release :)

**Comment by EvolveArt** [comment]
> Oh and no need for any version bumps; that'll be taken care of when we do a release :)

Thanks I do have something weird happening in my project tho :
When using my fork as a dependency it breaks all the other scale-info types implementations :(

You can checkout this [PR](https://github.com/keep-starknet-strange/madara/pull/667) to see

**Comment by jsdw** [comment]
> > Oh and no need for any version bumps; that'll be taken care of when we do a release :)
> 
> Thanks I do have something weird happening in my project tho : When using my fork as a dependency it breaks all the other scale-info types implementations :(
> 
> You can checkout this [PR](https://github.com/keep-starknet-strange/madara/pull/667) to see

I haven't checked, but I'm guessing it's because there are now multiple versions of scale-info in your cargo tree; use the cargo.toml patch stuff if you aren't already to ensure all scale-infos use your fork :)

**Comment by EvolveArt** [comment]
Great! Could we merge this ? @jsdw or anything blocking let me know

**Comment by jsdw** [comment]
> The clippy errors are possibly just new errors that appeared since rust was updated. The cleanest approach would be another PR that runs a clippy --fix etc to sort these out :)

This still needs fixing; I'll open a new PR to address those and then when this branch is updated and passing we can merge it!

**Comment by jsdw** [comment]
Edit: nevermind; re-ran the job and it passed!

**Pull request merged**
